---
title: "R Notebook"
output: html_notebook
---
```{r}
library(StatsBombR)
library(plotly)
library(reshape2)
library(ggsci)
library(viridis)
```


```{r}
AllCompet <- FreeCompetitions() %>% filter(competition_name=="Women's World Cup" & season_name=="2023")
AllMatches <- FreeMatches(AllCompet)

AllMatches <- AllMatches  %>%  mutate(away_team.away_team_name = gsub(" Women's","",away_team.away_team_name),
                                      home_team.home_team_name = gsub(" Women's","",home_team.home_team_name),
                                      .keep="unused")


AllMatches <- AllMatches  %>%  mutate(away_team.away_team_name = gsub(" ","",away_team.away_team_name),
                                      home_team.home_team_name = gsub(" ","",home_team.home_team_name),
                                      .keep="unused")

Events <- free_allevents(AllMatches)
Shots_All <- Events %>% filter(type.name=="Shot")

Shots_All <- Shots_All  %>%  mutate(team = gsub(" ","",team.name),
                                      .keep="unused")
#Goals_All <- Events %>% filter(type.name=="Goal")
```

```{r}
#view(Goal_All)
#view(Shots_All)
#view(AllMatches)
#view(Events)
```

#*Goals Visualization*
```{r}
Shots <- subset(Shots_All, select = c(shot.outcome.name,team, player.name))

Shots <- Shots  %>%  mutate(player = player.name,
                                      outcome = case_when(shot.outcome.name!="Goal" ~ 0,
                                                         shot.outcome.name=="Goal" ~ 1),
                                      team = gsub("Women's","",team),
                                      .keep="unused")


#view(Shots)
```

```{r}
Semifinals <- AllMatches %>% filter(competition_stage.name=="Semi-finals")
pays_semifinals <- subset(Semifinals, select = c(home_team.home_team_name,away_team.away_team_name))
pays_semifinals <- melt(pays_semifinals) %>% distinct() %>% as.list() %>% unlist() %>% sort() #select all teams
pays_semifinals_list <- melt(pays_semifinals) %>% distinct() %>% as.list() %>% unlist() %>% sort() %>% as.list() #select all teams
#view(pays_semifinals)

Quarterfinals <- AllMatches %>% filter(competition_stage.name=="Quarter-finals")
pays_quarterfinals <- subset(Quarterfinals, select = c(home_team.home_team_name,away_team.away_team_name))
pays_quarterfinals <- melt(pays_quarterfinals) %>% distinct() %>% as.list() %>% unlist() %>% sort() #select all teams
pays_quarterfinals <- setdiff(pays_quarterfinals, pays_semifinals)
pays_quarterfinals_list <- melt(pays_quarterfinals) %>% distinct() %>% as.list() %>% unlist() %>% sort() %>% as.list() #select all teams
#view(pays_quarterfinals)

Round_of_16 <- AllMatches %>% filter(competition_stage.name=="Round of 16")
pays_r16 <- subset(Round_of_16, select = c(home_team.home_team_name,away_team.away_team_name))
pays_r16 <- melt(pays_r16) %>% distinct() %>% as.list() %>% unlist() %>% sort() #select all teams
pays_r16 <- setdiff(pays_r16, union(pays_quarterfinals, pays_semifinals))
pays_r16_list <- melt(pays_r16) %>% distinct() %>% as.list() %>% unlist() %>% sort() %>% as.list() #select all teams
#view(pays_r16)

Group_Stage <- AllMatches %>% filter(competition_stage.name=="Group Stage")
pays_gs <- subset(Group_Stage, select = c(home_team.home_team_name,away_team.away_team_name))
pays_gs <- melt(pays_gs) %>% distinct() %>% as.list() %>% unlist() %>% sort() #select all teams
pays_r8 <- union(pays_quarterfinals, pays_semifinals)
pays_gs <- setdiff(pays_gs, union(pays_r16, pays_r8))
pays_gs_list <- melt(pays_gs) %>% distinct() %>% as.list() %>% unlist() %>% sort() %>% as.list() #select all teams
view(pays_gs)

# Créer un data frame pour l'échelle de couleur
color_scale_data_GS <- data.frame(team = pays_gs, group = "8-GS")
color_scale_data_R16 <- data.frame(team = pays_r16, group = "7-R16")
color_scale_data_Quarter <- data.frame(team = pays_quarterfinals, group = "6-Quarterfinals")
color_scale_data_Semi <- data.frame(team = pays_semifinals, group = "5-Semifinals")
color_scale_data_4 <- data.frame(team = "Australia", group = "4th")
color_scale_data_3 <- data.frame(team = "Sweden", group = "3rd")
color_scale_data_2 <- data.frame(team = "England", group = "2nd")
color_scale_data_1 <- data.frame(team = "Spain", group = "1st")
color_scale_data <- bind_rows(color_scale_data_GS, 
                              color_scale_data_R16, 
                              color_scale_data_Quarter, 
                              color_scale_data_Semi)
color_scale_2 <- bind_rows(color_scale_data_GS, 
                              color_scale_data_R16, 
                              color_scale_data_Quarter, 
                              color_scale_data_4, color_scale_data_3, color_scale_data_2, color_scale_data_1)

#view(color_scale_data)
```

##Player-by-player visualization

```{r}
df_shots_total <- aggregate(x = Shots$outcome, by = list(Shots$player), FUN = length)
df_shots_succeed <- aggregate(x = Shots$outcome, by = list(Shots$player), FUN = sum)

df <- merge(df_shots_succeed, df_shots_total, by=c("Group.1")) %>% mutate(player = Group.1,
                                                                               completed_shots = x.x,
                                                                               total_shots = x.y,
                                                                               .keep="unused")

df1 <- subset(Shots, selec = c(player, team))
view(df1)

df <- merge(df1, df, by=c("player"))
#view(df)
df <- df %>% distinct()

df <- df %>% mutate(shots_completion_ratio = completed_shots/total_shots,
                    total_shots = total_shots,
                    total_goals = completed_shots,
                    .keep = "unused")

print(length(df$player))
#view(df)

df <- df[df$total_shots>=4,] # Removing players that attempted less than 4 shots

print(length(df$player)) # 398 players attempted at least 1 shots in the WC

#We now have a df containing every player that shot at least once in the World cup, associated with how many shots they attempted, and their ratio of successful shots

pays = c("France", "England", "Spain", "Switzerland") #Select teams we wish to observe
#pays <- melt(df$team) %>% distinct() %>% as.list() %>% unlist() %>% sort() %>% as.list() #Select all teams

df_player <- df[df$team %in% pays,]
mean_shots_completion_ratio = mean(df$shots_completion_ratio)
mean_shots_nb = mean(df$total_shots)


df[nrow(df) + 1,] <- list("Mean Player", "Mean Player", mean_shots_nb, mean_shots_completion_ratio)
#view(df)

df$group <- ifelse(df$team %in% pays_gs, "8-GS",
                              ifelse(df$team %in% pays_r16, "7-R16",
                                     ifelse(df$team %in% pays_quarterfinals, "6-Quarterfinals","5-Semifinals")))
df$groupv2 <- ifelse(df$team %in% pays_gs, "8-GS",
                              ifelse(df$team %in% pays_r16, "7-R16",
                                     ifelse(df$team %in% pays_quarterfinals, "6-Quarterfinals",
                                            ifelse(df$team == "Australia", "4th",
                                                   ifelse(df$team == "Sweden", "3rd",
                                                          ifelse(df$team == "England", "2nd","1st"))))))
#view(df)
#p <- ggplot(df, aes(total_shots, shots_completion_ratio, label = paste("player =", player, ", team =", team ), color = group)) + geom_point() +  scale_colour_manual(values = colors)
#Couleur de base
#p <- ggplot(df, aes(total_shots, shots_completion_ratio, label = paste("player =", player, ", team =", team ), color = team)) + geom_point()

p <- ggplot(df, aes(total_shots, shots_completion_ratio, label = paste("player =", player, ", team =", team ), color = groupv2)) + geom_point() +  scale_color_viridis(discrete=TRUE)
ggplotly(p)
```

##Team-by-team visualization

```{r}
df_shots_total <- aggregate(x = Shots$outcome, by = list(Shots$player), FUN = length)
df_shots_succeed <- aggregate(x = Shots$outcome, by = list(Shots$player), FUN = sum)

df <- merge(df_shots_succeed, df_shots_total, by=c("Group.1")) %>% mutate(player = Group.1,
                                                                               completed_shots = x.x,
                                                                               total_shots = x.y,
                                                                               .keep="unused")

df1 <- subset(Shots, selec = c(player, team))
#view(df1)

df <- merge(df1, df, by=c("player"))
#view(df)
df <- df %>% distinct()

df <- df %>% mutate(shots_completion_ratio = completed_shots/total_shots,
                    total_shots = total_shots,
                    total_goals = completed_shots,
                    .keep = "unused")

print(length(df$player))
#view(df)

df <- df[df$total_shots>=1,] # Removing players that attempted less than 1 shots

print(length(df$player)) # 398 players attempted at least 1 shots in the WC

#We now have a df containing every player that shots at least once in the World cup, associated with how many shots they attempted, and their ratio of successful shots

#pays = c("France", "England", "Spain", "Switzerland") #Countries we wish to observe
#pays = c("Switzerland")
pays <- melt(df$team) %>% distinct() %>% as.list() %>% unlist() %>% sort() %>% as.list() #select all teams

#view(pays)

df_pays <- df[df$team %in% pays,]

for (i in 0:length(pays))
  df_pays[nrow(df_pays) + 1,] <- list(paste("",pays[i]), paste("", pays[i]), 
                                      sum(df_pays$total_shots[df_pays$team == pays[i]]), 
                                      0,
                                      sum(df_pays$total_goals[df_pays$team == pays[i]]))

df_pays <- subset(df_pays, select = -c(player))

n <- length(pays)

#view(df_pays)

dftail <- df_pays[(nrow(df_pays)-(n - 1)):nrow(df_pays),] %>% mutate(team = gsub(" ","",team),
                                                                     shots_completion_ratio = total_goals/total_shots,
                                                                     total_shots = total_shots,
                                                                     total_goals = total_goals,
                                                                     .keep = "unused")

#pays_gs <- pays_gs %>% mutate(team=gsub(" ","",x))

dftail$group <- ifelse(dftail$team %in% pays_gs, "8-GS",
                              ifelse(dftail$team %in% pays_r16, "7-R16",
                                     ifelse(dftail$team %in% pays_quarterfinals, "6-Quarterfinals","5-Semifinals")))
dftail$groupv2 <- ifelse(dftail$team %in% pays_gs, "8-GS",
                              ifelse(dftail$team %in% pays_r16, "7-R16",
                                     ifelse(dftail$team %in% pays_quarterfinals, "6-Quarterfinals",
                                            ifelse(dftail$team == "Australia", "4th",
                                                   ifelse(dftail$team == "Sweden", "3rd",
                                                          ifelse(dftail$team == "England", "2nd","1st"))))))

#view(dftail)

p <- ggplot(dftail, aes(total_shots, shots_completion_ratio, label=team, color = groupv2)) + geom_text(aes(fontface=2)) + scale_color_viridis(discrete=TRUE)

ggplotly(p)
```
##Comparaison xG to True Goal Ratio visualization

```{r}
Shots_exp <- subset(Shots_All, select = c(shot.statsbomb_xg,team, player.name))

Shots_exp <- Shots_exp  %>%  mutate(player = player.name,
                                      xg = shot.statsbomb_xg,
                                      team = gsub("Women's","",team),
                                      .keep="unused")

#view(Shots_exp)

df_shots_exp_succeed <- aggregate(x = Shots_exp$xg, by = list(Shots_exp$player), FUN = sum)
#df_shots_exp_succeed <- df_shots_exp_succeed %>% mutate(player=Group.1, 
#                               df_shots_exp_ratio=df_shots_exp_succeed/df_shots_exp_total)

#view(df_shots_exp_succeed)
colnames(df_shots_exp_succeed) <- c("player", "xG")
#view(df)
#view(df_shots_exp_succeed)
df2 <- merge(df, df_shots_exp_succeed, by=c("player"))
df2 <- df2 %>% mutate(xG_ratio = df_shots_exp_succeed$xG/total_shots)
#,                  .keep = "unused")

#view(df2)

print(length(df2$player))
#view(df2)

df2 <- df2[df2$total_shots>=2,] # Removing players that attempted less than 1 shots

print(length(df2$player)) # 398 players attempted at least 1 shots in the WC

#We now have a df containing every player that shots at least once in the World cup, associated with their xg

```

##Comparaison xG to True Goal Ratio visualization - Players

```{r}
pays = c("France", "England", "Spain", "Switzerland") #Select teams we wish to observe
pays <- melt(df$team) %>% distinct() %>% as.list() %>% unlist() %>% sort() %>% as.list() #Select all teams

df2_player <- df2[df2$team %in% pays,]
mean_shots_completion_ratio = mean(df2_player$shots_completion_ratio)
mean_shots_nb = mean(df2_player$total_shots)
mean_shots_xG = mean(df2_player$xG)
mean_shots_xG_ratio = mean(df2_player$xG_ratio)


df2_player[nrow(df2_player) + 1,] <- list("Mean Player", "Mean Player", mean_shots_nb, mean_shots_completion_ratio, mean_shots_xG, mean_shots_xG_ratio)


df2_player$group <- ifelse(df2_player$team %in% pays_gs, "8-GS",
                              ifelse(df2_player$team %in% pays_r16, "7-R16",
                                     ifelse(df2_player$team %in% pays_quarterfinals, "6-Quarterfinals","5-Semifinals")))
df2_player$groupv2 <- ifelse(df2_player$team %in% pays_gs, "8-GS",
                              ifelse(df2_player$team %in% pays_r16, "7-R16",
                                     ifelse(df2_player$team %in% pays_quarterfinals, "6-Quarterfinals",
                                            ifelse(df2_player$team == "Australia", "4th",
                                                   ifelse(df2_player$team == "Sweden", "3rd",
                                                          ifelse(df2_player$team == "England", "2nd","1st"))))))


#view(df2_player)

p <- ggplot(df2_player, aes(xG_ratio, shots_completion_ratio, size = total_shots, label = player, colour=groupv2)) + 
    geom_point(shape=21) + geom_abline(intercept = 0, slope = 1, linetype = "dashed") + scale_color_viridis(discrete=TRUE) #+ scale_y_log10()

ggplotly(p)
```
##Comparaison xG to True Goal Ratio visualization - Pays par Pays


```{r}
#pays2 = c("France", "England", "Spain", "Switzerland") #Countries we wish to observe
pays2 <- melt(df2$team) %>% distinct() %>% as.list() %>% unlist() %>% sort() %>% as.list() #select all teams

#view(pays2)

df2_pays <- df2[df2$team %in% pays2,]
#view(df2_pays)

for (i in 0:length(pays2))
  df2_pays[nrow(df2_pays) + 1, ] <- list(paste("",pays2[i]), paste("", pays2[i]),
                                        sum(df2_pays$total_shots[df2_pays$team == pays2[i]]),
                                        sum(df2_pays$shots_completion_ratio[df2_pays$team == pays2[i]]),
                                        sum(df2_pays$total_goals[df2_pays$team == pays2[i]]),
                                        sum(df2_pays$xG[df2_pays$team == pays2[i]]),
                                        0)
  
df2_pays <- subset(df2_pays, select = -c(player))

#view(df2_pays)
n <- length(pays2)

df2tail <- df2_pays[(nrow(df2_pays)-(n - 1)):nrow(df2_pays),]  %>% mutate(team = gsub(" ","",team),
                                                                      shots_completion_ratio = total_goals/total_shots,
                                                                     total_shots = total_shots,
                                                                     total_goals = total_goals,
                                                                     xG = xG,
                                                                     xG_ratio = xG/total_shots,
                                                                     .keep = "unused")

df2tail$group <- ifelse(df2tail$team %in% pays_gs, "8-GS",
                              ifelse(df2tail$team %in% pays_r16, "7-R16",
                                     ifelse(df2tail$team %in% pays_quarterfinals, "6-Quarterfinals","5-Semifinals")))
df2tail$groupv2 <- ifelse(df2tail$team %in% pays_gs, "8-GS",
                              ifelse(df2tail$team %in% pays_r16, "7-R16",
                                     ifelse(df2tail$team %in% pays_quarterfinals, "6-Quarterfinals",
                                            ifelse(df2tail$team == "Australia", "4th",
                                                   ifelse(df2tail$team == "Sweden", "3rd",
                                                          ifelse(df2tail$team == "England", "2nd","1st"))))))


#view(df2tail)


p <- ggplot(df2tail, aes(xG_ratio, shots_completion_ratio, size = total_shots, label=team, color = groupv2)) + geom_text(aes(fontface=3)) + geom_abline(intercept = 0, slope = 1, linetype = "dashed") + scale_color_viridis(discrete=TRUE)

ggplotly(p)
```


