---
title: "R Notebook"
output: html_notebook
---
```{r}
library(StatsBombR)
library(plotly)
library(reshape2)
```


```{r}
AllCompet <- FreeCompetitions() %>% filter(competition_name=="Women's World Cup" & season_name=="2023")
AllMatches <- FreeMatches(AllCompet)
Passes_All <- free_allevents(AllMatches) %>% filter(type.name=="Pass")
```


```{r}
Passes_All <- subset(Passes_All, select = c(pass.outcome.name,team.name, player.name))

Passes_All <- Passes_All  %>%  mutate(player = player.name,
                                      outcome = case_when(is.na(pass.outcome.name) ~ 1,
                                                         !is.na(pass.outcome.name) ~ 0),
                                      team = gsub(" Women's","",team.name),
                                      .keep="unused")

#View(Passes_All)
```

#Player-by-player visualization

```{r}
df_passes_totales <- aggregate(x = Passes_All$outcome, by = list(Passes_All$player), FUN = length)
df_passes_reussies <- aggregate(x = Passes_All$outcome, by = list(Passes_All$player), FUN = sum)

df <- merge(df_passes_reussies, df_passes_totales, by=c("Group.1")) %>% mutate(player = Group.1,
                                                                               completed_passes = x.x,
                                                                               total_passes = x.y,
                                                                               .keep="unused")

df1 <- subset(Passes_All, selec = c(player, team))
#view(df1)

df <- merge(df1, df, by=c("player"))

df <- df %>% distinct()

df <- df %>% mutate(pass_completion_ratio = completed_passes/total_passes,
                    total_passes = total_passes,
                    .keep = "unused")

#print(length(df$player))

df <- df[df$total_passes>=20,] # Removing players that attempted less than 50 passes

#print(length(df$player)) # 384 players attempted at least 50 passes in the WC

#We now have a df containing every player that passed at least once in the World cup, associated with how many passes they attempted, and their ratio of successful passes

pays = c("France", "England", "Spain", "Switzerland", "Average Player") #Select teams we wish to observe
pays <- melt(df$team) %>% distinct() %>% as.list() %>% unlist() %>% sort() %>% as.list() #Select all teams

df <- df[df$team %in% pays,]
mean_pass_completion_ratio = mean(df$pass_completion_ratio)
mean_pass_nb = mean(df$total_passes)


df[nrow(df) + 1,] <- list("Mean Player", "Mean Player", mean_pass_nb, mean_pass_completion_ratio)

#view(df)

p <- ggplot(df, aes(total_passes, pass_completion_ratio, label = player, colour=team)) + geom_point()
ggplotly(p)
```

#Team-by-team visualization

```{r}
df_passes_totales <- aggregate(x = Passes_All$outcome, by = list(Passes_All$player), FUN = length)
df_passes_reussies <- aggregate(x = Passes_All$outcome, by = list(Passes_All$player), FUN = sum)

df <- merge(df_passes_reussies, df_passes_totales, by=c("Group.1")) %>% mutate(player = Group.1,
                                                                               completed_passes = x.x,
                                                                               total_passes = x.y,
                                                                               .keep="unused")

df1 <- subset(Passes_All, select = c(player, team))
#view(df1)

df <- merge(df1, df, by=c("player"))

df <- df %>% distinct()

df <- df %>% mutate(pass_completion_ratio = completed_passes/total_passes,
                    total_passes = total_passes,
                    .keep = "unused")

#print(length(df$player))

df <- df[df$total_passes>=20,] # Removing players that attempted less than 50 passes

#print(length(df$player)) # 384 players attempted at least 50 passes in the WC

#We now have a df containing every player that passed at least once in the World cup, associated with how many passes they attempted, and their ratio of successful passes

#pays = c("France", "England", "Spain", "Switzerland") #Countries we wish to observe
pays <- melt(df$team) %>% distinct() %>% as.list() %>% unlist() %>% sort() %>% as.list() #select all teams

#view(pays)

df <- df[df$team %in% pays,]

for (i in 0:length(pays))
  df[nrow(df) + 1,] <- list(paste("",pays[i]), paste("", pays[i]), mean(df$total_passes[df$team == pays[i]]), mean(df$pass_completion_ratio[df$team == pays[i]]))

df <- subset(df, select = -c(player))

n <- length(pays)

dftail <- df[(nrow(df)-(n - 1)):nrow(df),]

#view(dftail)

p <- ggplot(dftail, aes(total_passes, pass_completion_ratio, colour=team)) + geom_point()
ggplotly(p)
```
